name: TraffiqueJam Mobile Marketing
favicon: null
layout_spectrum: 0.29628
typography_spectrum: 0.59471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8a8a8a'
    - '#019c47'
    - '#4f4f4f'
  brandStrength: 0.875
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
