typography_spectrum: 0.59471
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8a8a8a'
    - '#019c47'
    - '#4f4f4f'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.29628
analytics:
  google: null
  facebook: null
  twitter: null
name: TraffiqueJam Mobile Marketing
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cutting Edge Mobile Marketing
description: Solutions for Local Business - Nationwide
purpose: []
